### ISSUE TITLE
hello ,I wonder did you fix the problem you present at the below link.?

### ISSUE THREAD

**Issue by ttomchy** [ankurbaruah90/laser_camera_calibration#1]
https://stackoverflow.com/questions/46406330/2d-laser-camera-extrinsic-calibration-optimization-and-constraints

**Comment by ankurbaruah90** [comment]
@ttomchy Hi, sorry for the late response. I moved on to the matlab toolbox, RADLOCC. The toolbox specifies a format in which the laser scan data needs to be represented. The snaps of the calibration plane at various angles and orientations then need to be time synchronized with its corresponding laser scan data. Once you have this data, its fairly easy with the toolbox to calibrate the 2D laser and the monocular camera. You might need to calibrate your camera first using a similar toolbox named RADOCC. Both the packages are available at the link [http://www-personal.acfr.usyd.edu.au/akas9185/AutoCalib/index.html](url). The results are fair enough and mostly depends on the quality of the dataset.
